# Generated by Django 5.2.3 on 2025-07-13 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
    ]
